import { test, expect } from "@playwright/test";
import AxeBuilder from "@axe-core/playwright";
test("Tabs are underlined content navigation; SegmentedControl owns size and pill choices", async ({ page }) => {
	await page.goto("/#docs/tabs");
	const preview = page.getByRole("region", { name: "Interactive example" });
	const guide = preview.getByRole("tab", { name: "Guide", exact: true });
	await guide.click();
	await expect(preview.getByRole("tabpanel")).toHaveText("Design guide");
	await expect(guide).toHaveCSS("border-bottom-width", "2px");
	await expect(preview.locator(".mds-segment-indicator")).toHaveCount(0);
	expect((await new AxeBuilder({ page }).include(".docs-live-stage").analyze()).violations).toEqual([]);
	await page.goto("/#docs/segmented-control");
	const settings = page.getByRole("group", { name: "Example settings" });
	await settings.getByRole("combobox").nth(1).click();
	await page.getByRole("option", { name: "Pill", exact: true }).click();
	const group = preview.getByRole("radiogroup");
	await expect(group).toHaveAttribute("data-shape", "pill");
	await expect(group).toHaveCSS("border-radius", "999px");
	await settings.getByRole("combobox").first().click();
	await page.getByRole("option", { name: "Large", exact: true }).click();
	await expect(group).toHaveAttribute("data-size", "lg");
	await expect(group.getByRole("radio").first()).toHaveCSS("min-height", "44px");
});
