export const componentSections = [
	{
		id: "foundations",
		title: ["基础与布局", "Foundations & layout"],
		slugs: ["theme", "typography", "container", "grid", "divider", "atmosphere"],
	},
	{
		id: "actions",
		title: ["操作", "Actions"],
		slugs: ["button", "icon-button", "chip", "dropdown-menu", "choice-menu"],
	},
	{
		id: "forms",
		title: ["表单与输入", "Forms & input"],
		slugs: [
			"form",
			"field",
			"input",
			"textarea",
			"select",
			"cascader",
			"native-select",
			"checkbox",
			"radio",
			"radio-card",
			"switch",
			"slider",
			"segmented-control",
		],
	},
	{
		id: "dates",
		title: ["日期与时间", "Date & time"],
		slugs: ["date-field", "date-picker", "date-range-field", "date-range-picker", "time-field", "time-picker"],
	},
	{
		id: "navigation",
		title: ["导航", "Navigation"],
		slugs: [
			"navigation",
			"nav-drawer",
			"nav-rail",
			"mega-menu",
			"tabs",
			"anchor",
			"scroll-navigator",
			"pagination",
			"steps",
		],
	},
	{
		id: "display",
		title: ["内容与数据展示", "Content & data display"],
		slugs: [
			"card",
			"avatar",
			"avatar-group",
			"badge",
			"notification-badge",
			"list",
			"selection-list",
			"table",
			"data-table",
			"accordion",
			"collapse",
			"audio-player",
		],
	},
	{
		id: "feedback",
		title: ["状态与反馈", "Status & feedback"],
		slugs: ["callout", "banner", "toast", "progress", "spinner", "skeleton", "empty-state", "feature-highlight"],
	},
	{
		id: "overlays",
		title: ["浮层与搜索", "Overlays & search"],
		slugs: ["dialog", "side-sheet", "popover", "tooltip", "spotlight"],
	},
	{ id: "trends", title: ["趋势", "Trends"], slugs: ["line-chart", "area-chart"] },
	{ id: "comparison", title: ["比较与构成", "Comparison & composition"], slugs: ["bar-chart", "donut-chart"] },
] as const;
