export const componentNames: Record<string, string> = {
	theme: "主题提供器",
	toast: "通知",
	button: "按钮",
	"icon-button": "图标按钮",
	field: "表单字段",
	input: "输入框",
	textarea: "多行输入框",
	select: "选择器",
	"native-select": "原生选择器",
	checkbox: "复选框",
	switch: "开关",
	radio: "单选组",
	"radio-card": "单选卡片",
	"segmented-control": "分段控件",
	slider: "滑块",
	"choice-menu": "选项菜单",
	"dropdown-menu": "下拉菜单",
	dialog: "对话框",
	"side-sheet": "侧边面板",
	navigation: "导航栏",
	"nav-drawer": "导航抽屉",
	collapse: "折叠面板",
	accordion: "手风琴",
	tabs: "标签页",
	avatar: "头像",
	"avatar-group": "头像组",
	badge: "徽标",
	list: "列表",
	table: "表格",
	pagination: "分页",
	steps: "步骤条",
	progress: "进度条",
	skeleton: "骨架屏",
	tooltip: "工具提示",
	alert: "状态提示",
	"empty-state": "空状态",
	"line-chart": "折线图",
	"area-chart": "面积图",
	"bar-chart": "柱状图",
	"donut-chart": "环形图",
	icons: "图标",
	callout: "正文提示",
	banner: "顶部公告",
	card: "卡片",
	container: "容器",
	atmosphere: "柔和渐变",
};
export function componentTitle(entry: { slug: string; names: string[] }, locale: "zh" | "en", full = false) {
	const name = entry.slug === "icons" ? "Icons" : full && locale === "en" ? entry.names.join(" / ") : entry.names[0];
	return locale === "zh" ? `${componentNames[entry.slug]} ${name}` : name;
}
