// Generated from packages/icons/catalog/*.json. Do not edit directly.
export const iconCatalog = [
	{ name: "Accessibility", category: "everyday", keywords: ["accessibility", "inclusive", "person"] },
	{ name: "Activity", category: "data", keywords: ["活动曲线", "pulse", "心跳"] },
	{ name: "AddressBook", category: "communication", keywords: ["通讯录", "address", "directory"] },
	{ name: "AlarmClock", category: "everyday", keywords: ["闹钟", "alarm", "提醒"] },
	{ name: "AlertCircle", category: "everyday", keywords: ["警告", "错误", "warning", "error"] },
	{ name: "AlignBottom", category: "layout", keywords: ["底部对齐", "AlignBottom", "align bottom"] },
	{ name: "AlignCenter", category: "layout", keywords: ["水平居中", "AlignCenter", "align center"] },
	{ name: "AlignLeft", category: "layout", keywords: ["左对齐", "AlignLeft", "align left"] },
	{ name: "AlignMiddle", category: "layout", keywords: ["垂直居中", "AlignMiddle", "align middle"] },
	{ name: "AlignRight", category: "layout", keywords: ["右对齐", "AlignRight", "align right"] },
	{ name: "AlignTop", category: "layout", keywords: ["顶部对齐", "AlignTop", "align top"] },
	{ name: "Announcement", category: "communication", keywords: ["公告", "announcement", "bulletin"] },
	{ name: "Aperture", category: "media", keywords: ["光圈", "aperture", "shutter"] },
	{ name: "AppWindow", category: "layout", keywords: ["应用窗口", "AppWindow", "app window"] },
	{ name: "Archive", category: "files", keywords: ["归档", "archive", "storage", "box"] },
	{ name: "ArrowDown", category: "navigation", keywords: ["向下", "ArrowDown", "arrow down"] },
	{ name: "ArrowDownLeft", category: "navigation", keywords: ["左下", "ArrowDownLeft", "arrow down left"] },
	{ name: "ArrowDownRight", category: "navigation", keywords: ["右下", "ArrowDownRight", "arrow down right"] },
	{ name: "ArrowLeft", category: "navigation", keywords: ["向左", "返回", "back", "previous"] },
	{ name: "ArrowRight", category: "navigation", keywords: ["向右", "前进", "forward", "next"] },
	{ name: "ArrowUp", category: "navigation", keywords: ["向上", "ArrowUp", "arrow up"] },
	{ name: "ArrowUpDown", category: "navigation", keywords: ["swap", "vertical", "bidirectional"] },
	{ name: "ArrowUpLeft", category: "navigation", keywords: ["左上", "ArrowUpLeft", "arrow up left"] },
	{ name: "ArrowUpRight", category: "navigation", keywords: ["右上", "外链", "external", "northeast"] },
	{ name: "Asterisk", category: "editing", keywords: ["asterisk", "starburst", "eight spokes", "decoration"] },
	{ name: "AtSign", category: "communication", keywords: ["艾特", "at", "email", "address"] },
	{ name: "AudioWave", category: "media", keywords: ["音频波形", "waveform", "sound"] },
	{
		name: "BadgeCheck",
		category: "security",
		keywords: ["认证", "verified", "验证"],
		variants: ["outlined", "filled"],
	},
	{ name: "Ban", category: "security", keywords: ["block", "prohibited", "disabled"] },
	{ name: "Banknote", category: "business", keywords: ["纸币", "cash", "现金"] },
	{ name: "Battery", category: "development", keywords: ["电池", "energy", "电量"] },
	{ name: "BatteryCharging", category: "development", keywords: ["charging", "power", "battery"] },
	{
		name: "Bell",
		category: "communication",
		keywords: ["通知", "铃铛", "notification", "alert"],
		variants: ["outlined", "filled"],
	},
	{ name: "BellOff", category: "communication", keywords: ["通知关闭", "静音", "mute", "notifications"] },
	{ name: "BellRing", category: "communication", keywords: ["通知提醒", "响铃", "alert", "ring"] },
	{ name: "Binary", category: "development", keywords: ["二进制", "bits", "数字"] },
	{ name: "Blocks", category: "layout", keywords: ["组件", "积木", "components", "blocks"] },
	{ name: "Bold", category: "editing", keywords: ["加粗字体", "Bold", "bold"] },
	{ name: "Bolt", category: "everyday", keywords: ["flash", "lightning", "energy", "quick action"] },
	{
		name: "Bookmark",
		category: "files",
		keywords: ["收藏", "书签", "save", "bookmark"],
		variants: ["outlined", "filled"],
	},
	{ name: "BookmarkCheck", category: "communication", keywords: ["已收藏", "书签", "saved"] },
	{ name: "BookMarked", category: "files", keywords: ["书签书本", "saved", "reading"] },
	{ name: "BookmarkPlus", category: "communication", keywords: ["添加书签", "收藏", "add", "save"] },
	{ name: "BookOpen", category: "files", keywords: ["阅读", "打开书本", "read", "manual"] },
	{ name: "Braces", category: "editing", keywords: ["花括号对象", "Braces", "braces"] },
	{ name: "Briefcase", category: "business", keywords: ["公文包", "work", "工作"] },
	{ name: "BrowserWindow", category: "layout", keywords: ["浏览器窗口", "BrowserWindow", "browser window"] },
	{ name: "Brush", category: "media", keywords: ["画笔", "brush", "paint"] },
	{ name: "Bug", category: "development", keywords: ["缺陷", "debug", "虫子"] },
	{ name: "Building", category: "business", keywords: ["办公楼", "office", "企业"] },
	{ name: "Calculator", category: "data", keywords: ["计算器", "calculate", "计算"] },
	{ name: "Calendar", category: "everyday", keywords: ["日历", "date", "日期"] },
	{ name: "Camera", category: "media", keywords: ["相机", "camera", "capture"] },
	{ name: "CameraOff", category: "media", keywords: ["关闭相机", "camera", "disabled"] },
	{ name: "ChartArea", category: "data", keywords: ["面积图", "area", "面积"] },
	{ name: "ChartBar", category: "data", keywords: ["柱状图", "bars", "柱形"] },
	{ name: "ChartCandlestick", category: "data", keywords: ["蜡烛图", "candles", "K线"] },
	{ name: "ChartDonut", category: "data", keywords: ["环形图", "donut", "圆环"] },
	{ name: "ChartFunnel", category: "data", keywords: ["漏斗图", "funnel", "转化"] },
	{ name: "ChartLine", category: "data", keywords: ["折线图", "trend", "趋势"] },
	{ name: "ChartPie", category: "data", keywords: ["饼图", "pie", "占比"] },
	{ name: "ChartRadar", category: "data", keywords: ["雷达图", "radar", "多维"] },
	{ name: "ChartScatter", category: "data", keywords: ["散点图", "scatter", "分布"] },
	{ name: "Check", category: "editing", keywords: ["确认", "完成", "confirm", "done"] },
	{ name: "ChevronDown", category: "navigation", keywords: ["向下", "展开", "down", "expand"] },
	{ name: "ChevronLeft", category: "navigation", keywords: ["返回左侧", "ChevronLeft", "chevron left"] },
	{ name: "ChevronRight", category: "navigation", keywords: ["向右", "前进", "right", "next"] },
	{ name: "ChevronsDown", category: "navigation", keywords: ["快速向下", "ChevronsDown", "chevrons down"] },
	{ name: "ChevronsLeft", category: "navigation", keywords: ["快速向左", "ChevronsLeft", "chevrons left"] },
	{ name: "ChevronsRight", category: "navigation", keywords: ["快速向右", "ChevronsRight", "chevrons right"] },
	{ name: "ChevronsUp", category: "navigation", keywords: ["快速向上", "ChevronsUp", "chevrons up"] },
	{ name: "ChevronUp", category: "navigation", keywords: ["展开向上", "ChevronUp", "chevron up"] },
	{ name: "CircleCheck", category: "everyday", keywords: ["success", "complete", "confirmed"] },
	{ name: "CircleHelp", category: "everyday", keywords: ["help", "question", "support"] },
	{ name: "CircleX", category: "everyday", keywords: ["error", "failed", "cancel"] },
	{ name: "Clapperboard", category: "media", keywords: ["场记板", "movie", "production"] },
	{ name: "Clipboard", category: "editing", keywords: ["剪贴板粘贴", "Clipboard", "clipboard"] },
	{ name: "ClipboardCheck", category: "editing", keywords: ["核对清单", "ClipboardCheck", "clipboard check"] },
	{ name: "ClipboardPaste", category: "editing", keywords: ["paste", "clipboard", "insert"] },
	{ name: "Clock", category: "everyday", keywords: ["时钟", "time", "时间"] },
	{ name: "Cloud", category: "development", keywords: ["云", "infrastructure", "云服务"] },
	{ name: "CloudDownload", category: "development", keywords: ["cloud download", "sync", "restore"] },
	{ name: "CloudUpload", category: "development", keywords: ["cloud upload", "sync", "backup"] },
	{ name: "Code", category: "editing", keywords: ["代码语法", "Code", "code"] },
	{ name: "Coffee", category: "everyday", keywords: ["咖啡", "cup", "饮品"] },
	{ name: "Coins", category: "business", keywords: ["硬币", "money", "金币"] },
	{ name: "Columns2", category: "layout", keywords: ["双列布局", "Columns2", "columns 2"] },
	{ name: "Columns3", category: "layout", keywords: ["三列布局", "Columns3", "columns 3"] },
	{ name: "Compass", category: "navigation", keywords: ["指南针方向", "Compass", "compass"] },
	{ name: "Contact", category: "communication", keywords: ["联系人", "contact", "profile"] },
	{ name: "Container", category: "development", keywords: ["容器", "docker", "部署"] },
	{ name: "Copy", category: "editing", keywords: ["复制", "副本", "copy", "duplicate"] },
	{ name: "CornerDownLeft", category: "navigation", keywords: ["向左转下方", "CornerDownLeft", "corner down left"] },
	{ name: "CornerDownRight", category: "navigation", keywords: ["向右转下方", "CornerDownRight", "corner down right"] },
	{ name: "CornerUpLeft", category: "navigation", keywords: ["向左返回上方", "CornerUpLeft", "corner up left"] },
	{ name: "CornerUpRight", category: "navigation", keywords: ["向右返回上方", "CornerUpRight", "corner up right"] },
	{ name: "Cpu", category: "development", keywords: ["处理器", "chip", "芯片"] },
	{ name: "CreditCard", category: "business", keywords: ["银行卡", "payment", "支付"] },
	{ name: "Crop", category: "editing", keywords: ["裁切画布", "Crop", "crop"] },
	{ name: "Database", category: "development", keywords: ["数据库", "storage", "sql", "存储"] },
	{ name: "Design", category: "editing", keywords: ["bezier", "creative", "vector", "prototype"] },
	{ name: "Develop", category: "development", keywords: ["code", "software", "engineering", "browser"] },
	{ name: "Disc", category: "media", keywords: ["光盘", "optical", "disc", "cd"] },
	{
		name: "DistributeHorizontal",
		category: "layout",
		keywords: ["水平等距", "DistributeHorizontal", "distribute horizontal"],
	},
	{
		name: "DistributeVertical",
		category: "layout",
		keywords: ["垂直等距", "DistributeVertical", "distribute vertical"],
	},
	{ name: "DocumentScan", category: "files", keywords: ["扫描文档", "scan", "page"] },
	{ name: "DocumentStack", category: "files", keywords: ["文档集合", "stack", "files"] },
	{ name: "Download", category: "files", keywords: ["下载", "保存", "download", "save"] },
	{ name: "Droplet", category: "everyday", keywords: ["水滴", "water", "水"] },
	{ name: "Eraser", category: "editing", keywords: ["橡皮擦除", "Eraser", "eraser"] },
	{ name: "Ethernet", category: "development", keywords: ["网口", "port", "网络接口"] },
	{ name: "Expand", category: "layout", keywords: ["扩展尺寸", "Expand", "expand"] },
	{ name: "ExternalLink", category: "navigation", keywords: ["外部链接", "新窗口", "external", "open"] },
	{ name: "Eye", category: "security", keywords: ["可见", "visible", "查看"] },
	{ name: "EyeOff", category: "security", keywords: ["隐藏", "hidden", "不可见"] },
	{ name: "FastForward", category: "media", keywords: ["快进", "fast", "forward"] },
	{ name: "Fence", category: "security", keywords: ["访问边界", "boundary", "隔离"] },
	{ name: "File", category: "files", keywords: ["文件", "document", "blank"] },
	{ name: "FileArchive", category: "files", keywords: ["压缩文件", "zip", "compressed"] },
	{ name: "FileAudio", category: "files", keywords: ["音频文件", "audio", "file"] },
	{ name: "FileBookmark", category: "files", keywords: ["书签文档", "bookmarked", "file"] },
	{ name: "FileCode", category: "files", keywords: ["代码文件", "source", "script"] },
	{ name: "FileImage", category: "files", keywords: ["图像文件", "photo", "file"] },
	{ name: "FilePlus", category: "files", keywords: ["new file", "add document", "create"] },
	{ name: "FileSearch", category: "files", keywords: ["查找文件", "find", "document"] },
	{ name: "FileSignature", category: "files", keywords: ["签署文件", "signed", "document"] },
	{ name: "FileSpreadsheet", category: "files", keywords: ["电子表格", "excel", "cells"] },
	{ name: "FileText", category: "files", keywords: ["文档", "文本", "text", "document"] },
	{ name: "FileTransfer", category: "files", keywords: ["文件传输", "transfer", "documents"] },
	{ name: "FileVideo", category: "files", keywords: ["视频文件", "movie", "file"] },
	{ name: "Film", category: "media", keywords: ["电影", "film", "reel"] },
	{ name: "Filter", category: "data", keywords: ["筛选", "filter", "过滤"] },
	{ name: "Fingerprint", category: "security", keywords: ["指纹", "biometric", "生物识别"] },
	{ name: "Flag", category: "communication", keywords: ["标记", "flag", "report"], variants: ["outlined", "filled"] },
	{ name: "Flame", category: "everyday", keywords: ["火焰", "fire", "热门"] },
	{ name: "Flower", category: "everyday", keywords: ["花朵", "bloom", "花"] },
	{ name: "Folder", category: "files", keywords: ["文件夹", "directory"] },
	{ name: "FolderHeart", category: "files", keywords: ["收藏文件夹", "favorite", "directory"] },
	{ name: "FolderLock", category: "files", keywords: ["私密文件夹", "protected", "directory"] },
	{ name: "FolderOpen", category: "files", keywords: ["打开文件夹", "browse", "directory"] },
	{ name: "FolderPlus", category: "files", keywords: ["new folder", "add directory", "create"] },
	{ name: "FolderShared", category: "files", keywords: ["共享文件夹", "shared", "folder"] },
	{ name: "FolderTree", category: "files", keywords: ["目录树", "filesystem", "hierarchy"] },
	{ name: "Fullscreen", category: "layout", keywords: ["全屏展示", "Fullscreen", "fullscreen"] },
	{ name: "Gauge", category: "data", keywords: ["仪表盘", "meter", "指标"] },
	{ name: "Gift", category: "business", keywords: ["礼物", "present", "礼品"] },
	{ name: "GitBranch", category: "development", keywords: ["分支", "version", "git", "版本"] },
	{ name: "GitMerge", category: "development", keywords: ["合并", "git", "merge", "分支合并"] },
	{ name: "Globe", category: "everyday", keywords: ["地球", "world", "全球"] },
	{ name: "Gpu", category: "development", keywords: ["graphics card", "accelerator", "compute", "video hardware"] },
	{ name: "Grid2", category: "layout", keywords: ["四宫格", "Grid2", "grid 2"] },
	{ name: "Grid3", category: "layout", keywords: ["九宫格", "Grid3", "grid 3"] },
	{ name: "GripVertical", category: "editing", keywords: ["drag handle", "reorder", "move"] },
	{ name: "Guitar", category: "media", keywords: ["吉他", "guitar", "instrument"] },
	{ name: "Handshake", category: "business", keywords: ["合作", "agreement", "握手"] },
	{ name: "HardDrive", category: "development", keywords: ["硬盘", "disk", "磁盘"] },
	{ name: "Hash", category: "communication", keywords: ["话题", "频道", "hashtag", "channel"] },
	{ name: "Heading", category: "editing", keywords: ["标题", "Heading", "heading"] },
	{ name: "Heading1", category: "editing", keywords: ["一级标题", "Heading1", "heading 1"] },
	{ name: "Heading2", category: "editing", keywords: ["二级标题", "Heading2", "heading 2"] },
	{ name: "Headphones", category: "media", keywords: ["耳机", "headphones", "listen"] },
	{ name: "Heart", category: "everyday", keywords: ["爱心", "favorite", "喜欢"], variants: ["outlined", "filled"] },
	{ name: "HeartHandshake", category: "communication", keywords: ["关爱", "合作", "支持", "support", "care"] },
	{ name: "Highlighter", category: "editing", keywords: ["高亮标记", "Highlighter", "highlighter"] },
	{ name: "History", category: "everyday", keywords: ["history", "recent", "time"] },
	{ name: "Home", category: "navigation", keywords: ["首页主页", "Home", "home"] },
	{ name: "Hourglass", category: "everyday", keywords: ["沙漏", "duration", "等待"] },
	{ name: "IdCard", category: "security", keywords: ["身份卡", "identity", "证件"] },
	{ name: "Image", category: "media", keywords: ["图片", "image", "picture", "photo"] },
	{ name: "Images", category: "media", keywords: ["图库", "images", "gallery", "photos"] },
	{ name: "Inbox", category: "communication", keywords: ["收件箱", "接收", "inbox", "receive"] },
	{ name: "Indent", category: "editing", keywords: ["增加缩进", "Indent", "indent"] },
	{ name: "Info", category: "everyday", keywords: ["信息", "提示", "info", "help"] },
	{ name: "Italic", category: "editing", keywords: ["斜体", "Italic", "italic"] },
	{ name: "Kanban", category: "layout", keywords: ["看板任务", "Kanban", "kanban"] },
	{ name: "Key", category: "security", keywords: ["密钥", "password", "钥匙"] },
	{ name: "Keyboard", category: "development", keywords: ["keyboard", "typing", "autofill"] },
	{ name: "KeyRound", category: "security", keywords: ["访问令牌", "token", "access", "令牌"] },
	{ name: "Landmark", category: "business", keywords: ["银行", "bank", "机构"] },
	{ name: "Languages", category: "everyday", keywords: ["language", "translate", "localization"] },
	{ name: "Laptop", category: "development", keywords: ["笔记本电脑", "computer", "电脑"] },
	{ name: "Layers", category: "layout", keywords: ["图层叠加", "Layers", "layers"] },
	{ name: "LayoutDashboard", category: "layout", keywords: ["仪表盘", "布局", "dashboard", "overview"] },
	{ name: "LayoutList", category: "layout", keywords: ["列表布局", "LayoutList", "layout list"] },
	{ name: "Leaf", category: "everyday", keywords: ["叶子", "nature", "自然"] },
	{ name: "Library", category: "files", keywords: ["文库", "图书馆", "library", "collection"] },
	{ name: "Lightbulb", category: "everyday", keywords: ["灯泡", "idea", "灵感"] },
	{ name: "Link", category: "editing", keywords: ["链接连接", "Link", "link"] },
	{ name: "LinkCopy", category: "communication", keywords: ["复制链接", "copy", "link"] },
	{ name: "LinkOff", category: "communication", keywords: ["断开链接", "unlink", "broken"] },
	{ name: "ListBullets", category: "editing", keywords: ["无序列表", "ListBullets", "list bullets"] },
	{ name: "ListOrdered", category: "editing", keywords: ["有序列表", "ListOrdered", "list ordered"] },
	{ name: "LoaderCircle", category: "everyday", keywords: ["加载", "等待", "loading", "spinner"] },
	{ name: "Locate", category: "navigation", keywords: ["定位当前", "Locate", "locate"] },
	{ name: "Lock", category: "security", keywords: ["锁定", "locked", "锁"] },
	{ name: "LogIn", category: "navigation", keywords: ["登录进入", "LogIn", "log in"] },
	{ name: "LogOut", category: "navigation", keywords: ["登出退出", "LogOut", "log out"] },
	{ name: "Mail", category: "communication", keywords: ["邮件", "email", "envelope"] },
	{ name: "MailHeart", category: "communication", keywords: ["邮件", "喜欢", "favorite", "mail"] },
	{ name: "MailOpen", category: "communication", keywords: ["已读邮件", "open", "envelope"] },
	{ name: "MailPlus", category: "communication", keywords: ["邮件", "新建", "compose", "mail"] },
	{ name: "MapPin", category: "navigation", keywords: ["位置地点", "MapPin", "map pin"] },
	{ name: "Maximize", category: "layout", keywords: ["最大化", "Maximize", "maximize"] },
	{ name: "Medal", category: "business", keywords: ["奖牌", "achievement", "勋章"] },
	{ name: "Megaphone", category: "communication", keywords: ["扩音器", "broadcast", "megaphone"] },
	{ name: "MemoryStick", category: "development", keywords: ["内存", "ram", "内存条"] },
	{ name: "Mention", category: "communication", keywords: ["提及", "mention", "notify"] },
	{ name: "Menu", category: "navigation", keywords: ["菜单", "导航", "navigation", "hamburger"] },
	{ name: "Message", category: "communication", keywords: ["聊天", "chat", "bubble"] },
	{ name: "MessageCheck", category: "communication", keywords: ["消息已送达", "delivered", "read"] },
	{ name: "MessageForward", category: "communication", keywords: ["转发消息", "forward", "comment"] },
	{ name: "MessageHeart", category: "communication", keywords: ["喜欢评论", "爱心消息", "reaction", "love"] },
	{ name: "MessagePlus", category: "communication", keywords: ["新增评论", "新建消息", "comment", "add"] },
	{ name: "MessageReply", category: "communication", keywords: ["回复消息", "reply", "comment"] },
	{ name: "Messages", category: "communication", keywords: ["对话", "会话", "conversations"] },
	{ name: "MessageSquare", category: "communication", keywords: ["消息", "message", "comment"] },
	{ name: "MessageTyping", category: "communication", keywords: ["正在输入", "typing", "chat"] },
	{ name: "MessageUnread", category: "communication", keywords: ["未读", "消息", "unread", "message"] },
	{ name: "Microphone", category: "media", keywords: ["麦克风", "microphone", "record"] },
	{ name: "MicrophoneOff", category: "media", keywords: ["麦克风关闭", "mic", "mute"] },
	{ name: "Minimize", category: "layout", keywords: ["最小化", "Minimize", "minimize"] },
	{ name: "Minus", category: "editing", keywords: ["减少", "删除", "remove", "subtract"] },
	{ name: "Monitor", category: "development", keywords: ["显示器", "desktop", "桌面"] },
	{ name: "Moon", category: "everyday", keywords: ["月亮", "深色", "dark", "night"] },
	{ name: "MoreHorizontal", category: "navigation", keywords: ["更多", "操作", "more", "overflow"] },
	{ name: "MoreVertical", category: "navigation", keywords: ["more", "overflow", "kebab menu"] },
	{ name: "Move", category: "navigation", keywords: ["自由移动", "Move", "move"] },
	{ name: "MoveHorizontal", category: "navigation", keywords: ["水平移动", "MoveHorizontal", "move horizontal"] },
	{ name: "MoveVertical", category: "navigation", keywords: ["垂直移动", "MoveVertical", "move vertical"] },
	{ name: "Music", category: "media", keywords: ["音乐", "music", "notes"] },
	{ name: "MusicQueue", category: "media", keywords: ["播放队列", "playlist", "queue"] },
	{ name: "Network", category: "development", keywords: ["网络拓扑", "topology", "网络"] },
	{ name: "Notebook", category: "files", keywords: ["笔记本", "notes", "journal"] },
	{ name: "NotificationDot", category: "communication", keywords: ["未读", "通知", "红点", "unread", "notification"] },
	{ name: "Outdent", category: "editing", keywords: ["减少缩进", "Outdent", "outdent"] },
	{ name: "Package", category: "business", keywords: ["包裹", "parcel", "物流"] },
	{ name: "Paintbrush", category: "editing", keywords: ["画笔绘画", "Paintbrush", "paintbrush"] },
	{ name: "PaintBucket", category: "editing", keywords: ["填充颜色", "PaintBucket", "paint bucket"] },
	{ name: "Palette", category: "media", keywords: ["调色板", "palette", "colors"] },
	{ name: "PanelBottom", category: "layout", keywords: ["底部面板", "PanelBottom", "panel bottom"] },
	{ name: "PanelLeftClose", category: "layout", keywords: ["关闭侧栏", "collapse", "sidebar"] },
	{ name: "PanelLeftOpen", category: "layout", keywords: ["打开侧栏", "expand", "sidebar"] },
	{ name: "PanelRight", category: "layout", keywords: ["右侧面板", "PanelRight", "panel right"] },
	{ name: "PanelTop", category: "layout", keywords: ["顶部面板", "PanelTop", "panel top"] },
	{ name: "Paperclip", category: "editing", keywords: ["附件回形针", "Paperclip", "paperclip"] },
	{ name: "Paragraph", category: "files", keywords: ["段落", "paragraph", "pilcrow"] },
	{ name: "Pause", category: "media", keywords: ["暂停", "pause"] },
	{ name: "Pencil", category: "editing", keywords: ["铅笔编辑", "Pencil", "pencil"] },
	{ name: "PenTool", category: "editing", keywords: ["钢笔路径", "PenTool", "pen tool"] },
	{ name: "Percent", category: "data", keywords: ["百分比", "percentage", "百分率"] },
	{ name: "Phone", category: "communication", keywords: ["电话", "telephone", "call"] },
	{ name: "PhoneIncoming", category: "communication", keywords: ["来电", "incoming", "call"] },
	{ name: "PhoneOff", category: "communication", keywords: ["挂断电话", "hangup", "decline"] },
	{ name: "PhoneOutgoing", category: "communication", keywords: ["拨出电话", "outgoing", "call"] },
	{ name: "Piano", category: "media", keywords: ["钢琴键盘", "piano", "keyboard"] },
	{ name: "PictureInPicture", category: "layout", keywords: ["画中画", "PictureInPicture", "picture in picture"] },
	{ name: "Pin", category: "communication", keywords: ["置顶", "固定", "pin"] },
	{ name: "Play", category: "media", keywords: ["播放", "play", "start"] },
	{ name: "Plug", category: "development", keywords: ["插头", "connect", "电源连接"] },
	{ name: "Plus", category: "editing", keywords: ["添加", "增加", "add", "create"] },
	{ name: "Podcast", category: "media", keywords: ["播客", "podcast"] },
	{ name: "Power", category: "development", keywords: ["电源", "shutdown", "开关机"] },
	{ name: "Presentation", category: "files", keywords: ["演示文稿", "slides", "presentation"] },
	{ name: "Printer", category: "files", keywords: ["print", "paper", "document"] },
	{ name: "Quote", category: "editing", keywords: ["引用引文", "Quote", "quote"] },
	{ name: "Radio", category: "media", keywords: ["收音机", "radio", "broadcast"] },
	{ name: "Reaction", category: "communication", keywords: ["回应", "反应", "reaction", "emoji"] },
	{ name: "Receipt", category: "business", keywords: ["收据", "invoice", "发票"] },
	{ name: "Redo", category: "navigation", keywords: ["重做", "Redo", "redo"] },
	{ name: "Refresh", category: "navigation", keywords: ["刷新同步", "Refresh", "refresh"] },
	{ name: "Reply", category: "communication", keywords: ["回复", "reply", "back"] },
	{ name: "ReplyAll", category: "communication", keywords: ["回复全部", "reply", "all"] },
	{ name: "ReplyQuote", category: "communication", keywords: ["引用回复", "quote", "reply"] },
	{ name: "Restart", category: "development", keywords: ["restart", "reboot", "reload"] },
	{ name: "Rewind", category: "media", keywords: ["快退", "rewind"] },
	{ name: "Rocket", category: "everyday", keywords: ["火箭", "launch", "启动"] },
	{ name: "RotateLeft", category: "navigation", keywords: ["逆时针旋转", "RotateLeft", "rotate left"] },
	{ name: "RotateRight", category: "navigation", keywords: ["顺时针旋转", "RotateRight", "rotate right"] },
	{ name: "Route", category: "navigation", keywords: ["路线流程路径", "Route", "route"] },
	{ name: "Rows2", category: "layout", keywords: ["双行布局", "Rows2", "rows 2"] },
	{ name: "Rows3", category: "layout", keywords: ["三行布局", "Rows3", "rows 3"] },
	{ name: "Rss", category: "communication", keywords: ["订阅", "rss", "feed"] },
	{ name: "Ruler", category: "editing", keywords: ["标尺测量", "Ruler", "ruler"] },
	{ name: "Save", category: "files", keywords: ["save", "disk", "persist"] },
	{ name: "Scale", category: "business", keywords: ["天平", "balance", "公平"] },
	{ name: "ScanFace", category: "security", keywords: ["人脸识别", "faceid", "面容"] },
	{ name: "Scissors", category: "editing", keywords: ["剪切裁剪", "Scissors", "scissors"] },
	{ name: "ScrollText", category: "files", keywords: ["卷轴", "scroll", "manuscript"] },
	{ name: "Search", category: "navigation", keywords: ["搜索", "查找", "find", "lookup"] },
	{ name: "SelectAll", category: "editing", keywords: ["select all", "selection", "text"] },
	{ name: "Send", category: "communication", keywords: ["发送", "send", "paper", "plane"] },
	{ name: "SendHorizontal", category: "communication", keywords: ["发送", "send", "message"] },
	{ name: "Server", category: "development", keywords: ["服务器", "hosting", "主机"] },
	{ name: "Settings", category: "development", keywords: ["设置", "齿轮", "settings", "preferences"] },
	{ name: "Share", category: "communication", keywords: ["分享", "share", "social"] },
	{ name: "ShareForward", category: "communication", keywords: ["分享", "转发", "forward"] },
	{ name: "ShareUp", category: "communication", keywords: ["分享", "导出", "export", "upload"] },
	{ name: "Shield", category: "security", keywords: ["安全盾牌", "protection", "防护"] },
	{ name: "ShieldCheck", category: "security", keywords: ["安全", "检查", "protect", "verified"] },
	{ name: "ShoppingBag", category: "business", keywords: ["购物袋", "bag", "购买"] },
	{ name: "ShoppingCart", category: "business", keywords: ["购物车", "cart", "购物"] },
	{ name: "Shrink", category: "layout", keywords: ["收缩尺寸", "Shrink", "shrink"] },
	{ name: "Sidebar", category: "layout", keywords: ["侧边栏", "Sidebar", "sidebar"] },
	{ name: "Sigma", category: "data", keywords: ["求和", "sum", "总和"] },
	{ name: "Siren", category: "security", keywords: ["警报器", "alarm", "警报"] },
	{ name: "SkipBack", category: "media", keywords: ["上一首", "previous", "track", "skip", "back"] },
	{ name: "SkipForward", category: "media", keywords: ["下一首", "next", "track", "skip", "forward"] },
	{ name: "SlidersHorizontal", category: "layout", keywords: ["筛选", "调整", "filter", "adjust"] },
	{ name: "Smartphone", category: "development", keywords: ["手机", "mobile", "移动端"] },
	{ name: "Smile", category: "communication", keywords: ["表情", "开心", "smile", "emoji"] },
	{ name: "SortAscending", category: "navigation", keywords: ["sort", "ascending", "order"] },
	{ name: "SortDescending", category: "navigation", keywords: ["sort", "descending", "order"] },
	{ name: "Sparkle", category: "editing", keywords: ["sparkle", "four-point star", "highlight", "decoration"] },
	{ name: "SplitHorizontal", category: "layout", keywords: ["水平拆分", "SplitHorizontal", "split horizontal"] },
	{ name: "SplitVertical", category: "layout", keywords: ["垂直拆分", "SplitVertical", "split vertical"] },
	{ name: "Stamp", category: "files", keywords: ["印章", "stamp", "certify"] },
	{ name: "Star", category: "everyday", keywords: ["星标", "favorite", "收藏"], variants: ["outlined", "filled"] },
	{ name: "Stop", category: "media", keywords: ["停止", "stop"] },
	{ name: "Store", category: "business", keywords: ["商店", "shop", "门店"] },
	{ name: "Strikethrough", category: "editing", keywords: ["删除线", "Strikethrough", "strikethrough"] },
	{ name: "Subscript", category: "editing", keywords: ["下标", "Subscript", "subscript"] },
	{ name: "Sun", category: "everyday", keywords: ["太阳", "浅色", "light", "day"] },
	{ name: "Superscript", category: "editing", keywords: ["上标", "Superscript", "superscript"] },
	{ name: "Table", category: "layout", keywords: ["表格数据", "Table", "table"] },
	{ name: "TableOfContents", category: "files", keywords: ["目录索引", "contents", "index"] },
	{ name: "Tablet", category: "development", keywords: ["平板电脑", "device", "设备"] },
	{ name: "Tag", category: "business", keywords: ["标签", "price", "价格"] },
	{ name: "Tags", category: "files", keywords: ["多个标签", "labels", "taxonomy"] },
	{ name: "Target", category: "data", keywords: ["目标", "goal", "靶心"] },
	{ name: "TeamChat", category: "communication", keywords: ["团队讨论", "group", "conversation"] },
	{ name: "Terminal", category: "development", keywords: ["终端", "console", "shell", "命令行"] },
	{ name: "TextCursor", category: "editing", keywords: ["文字光标", "TextCursor", "text cursor"] },
	{ name: "ThumbsDown", category: "communication", keywords: ["不赞", "dislike", "disapprove"] },
	{ name: "ThumbsUp", category: "communication", keywords: ["赞", "like", "approve"] },
	{ name: "Ticket", category: "business", keywords: ["票券", "coupon", "优惠券"] },
	{ name: "Trash", category: "files", keywords: ["删除", "垃圾桶", "delete", "remove"] },
	{ name: "TrendingDown", category: "data", keywords: ["下降趋势", "decrease", "下降"] },
	{ name: "TrendingUp", category: "data", keywords: ["上升趋势", "increase", "增长"] },
	{ name: "TriangleAlert", category: "everyday", keywords: ["warning", "caution", "alert"] },
	{ name: "Trophy", category: "business", keywords: ["奖杯", "award", "冠军"] },
	{ name: "Truck", category: "business", keywords: ["卡车", "delivery", "运输"] },
	{ name: "TurnLeft", category: "navigation", keywords: ["左转", "TurnLeft", "turn left"] },
	{ name: "TurnRight", category: "navigation", keywords: ["右转", "TurnRight", "turn right"] },
	{ name: "Type", category: "editing", keywords: ["字体文本", "Type", "type"] },
	{ name: "Umbrella", category: "everyday", keywords: ["雨伞", "rain", "雨"] },
	{ name: "Underline", category: "editing", keywords: ["下划线", "Underline", "underline"] },
	{ name: "Undo", category: "navigation", keywords: ["撤销", "Undo", "undo"] },
	{ name: "Unlink", category: "editing", keywords: ["取消链接", "Unlink", "unlink"] },
	{ name: "Unlock", category: "security", keywords: ["解锁", "unlocked", "开锁"] },
	{ name: "Upload", category: "files", keywords: ["上传", "发送", "upload", "send"] },
	{ name: "User", category: "security", keywords: ["用户", "个人", "user", "account"] },
	{ name: "UserCheck", category: "communication", keywords: ["已关注", "用户确认", "following", "verified"] },
	{ name: "UserHeart", category: "communication", keywords: ["关注用户", "favorite", "person"] },
	{ name: "UserMinus", category: "security", keywords: ["remove user", "revoke", "account"] },
	{ name: "UserPlus", category: "security", keywords: ["add user", "invite", "account"] },
	{ name: "UserRound", category: "security", keywords: ["账户", "account", "个人资料"] },
	{ name: "Users", category: "security", keywords: ["用户组", "team", "团队"] },
	{ name: "Utensils", category: "everyday", keywords: ["餐具", "food", "餐饮"] },
	{ name: "Variable", category: "data", keywords: ["变量", "formula", "公式"] },
	{ name: "Vault", category: "security", keywords: ["保险柜", "safe", "保管"] },
	{ name: "Video", category: "media", keywords: ["视频", "video", "recording"] },
	{ name: "VideoCall", category: "communication", keywords: ["视频通话", "video", "meeting"] },
	{ name: "VinylRecord", category: "media", keywords: ["黑胶唱片", "vinyl", "record"] },
	{ name: "Volume", category: "media", keywords: ["音量", "volume", "speaker"] },
	{ name: "VolumeLow", category: "media", keywords: ["低音量", "quiet", "volume", "low"] },
	{ name: "VolumeOff", category: "media", keywords: ["静音", "mute", "audio", "off"] },
	{ name: "Wallet", category: "business", keywords: ["钱包", "balance", "余额"] },
	{ name: "WandSparkles", category: "editing", keywords: ["writing tools", "magic", "enhance"] },
	{ name: "Waypoints", category: "data", keywords: ["数据节点", "graph", "关系图"] },
	{ name: "Webhook", category: "development", keywords: ["回调", "callback", "钩子"] },
	{ name: "Wifi", category: "development", keywords: ["无线网络", "wireless", "无线"] },
	{ name: "WifiOff", category: "development", keywords: ["offline", "no connection", "wireless"] },
	{ name: "WindowCenter", category: "layout", keywords: ["window", "center", "position"] },
	{ name: "WindowClose", category: "layout", keywords: ["window", "close", "remove"] },
	{ name: "WindowFill", category: "layout", keywords: ["window", "fill", "resize"] },
	{ name: "WindowMaximize", category: "layout", keywords: ["window", "maximize", "zoom"] },
	{ name: "WindowMinimize", category: "layout", keywords: ["window", "minimize", "desktop"] },
	{ name: "Workflow", category: "development", keywords: ["工作流", "automation", "自动化"] },
	{ name: "X", category: "editing", keywords: ["关闭", "取消", "close", "cancel"] },
	{ name: "ZoomIn", category: "navigation", keywords: ["magnify", "zoom in", "enlarge"] },
	{ name: "ZoomOut", category: "navigation", keywords: ["magnify", "zoom out", "reduce"] },
] as const;
export type IconName = (typeof iconCatalog)[number]["name"];
export type IconCategory = (typeof iconCatalog)[number]["category"];
