export const showcaseCatalog = [
	{
		id: "overview",
		audience: "business",
		title: ["运行概览", "Operations overview"],
		description: ["指标、调用记录与服务状态。", "Metrics, request activity and service health."],
		components: ["Table", "Badge", "Card"],
		motif: "01",
	},
	{
		id: "policy",
		audience: "business",
		title: ["策略工作台", "Policy workspace"],
		description: ["配置防护规则并保存策略。", "Configure protection rules and save policies."],
		components: ["Select", "Switch", "Form"],
		motif: "02",
	},
	{
		id: "showcase-projects",
		audience: "business",
		title: ["项目协作", "Project workspace"],
		description: ["创建任务、推进看板并跟踪交付。", "Create tasks, advance the board and track delivery."],
		components: ["Card", "Form", "Progress"],
		motif: "03",
	},
	{
		id: "showcase-crm",
		audience: "business",
		title: ["销售客户管理", "Sales CRM"],
		description: ["搜索客户、查看商机并推进销售阶段。", "Find accounts, review opportunities and update stages."],
		components: ["Table", "Select", "Input"],
		motif: "04",
	},
	{
		id: "showcase-support",
		audience: "business",
		title: ["客服收件箱", "Support inbox"],
		description: ["回复客户、查看上下文并解决工单。", "Reply to customers, review context and resolve tickets."],
		components: ["Tabs", "Textarea", "Badge"],
		motif: "05",
	},
	{
		id: "showcase-team",
		audience: "business",
		title: ["团队与权限", "People & access"],
		description: ["添加成员、调整角色并配置登录要求。", "Add members, adjust roles and configure sign-in."],
		components: ["Avatar", "Select", "Switch"],
		motif: "06",
	},
	{
		id: "showcase-billing",
		audience: "business",
		title: ["订阅与账单", "Plans & billing"],
		description: ["比较方案、切换周期并确认变更。", "Compare plans, switch billing cycles and confirm changes."],
		components: ["SegmentedControl", "RadioCard", "Dialog"],
		motif: "07",
	},
	{
		id: "showcase-shop",
		audience: "consumer",
		title: ["生活方式商店", "Lifestyle shop"],
		description: ["查看商品、选择颜色与数量并加入购物袋。", "Explore a product, pick a finish and add it to your bag."],
		components: ["RadioCard", "Select", "Accordion"],
		motif: "08",
	},
	{
		id: "showcase-travel",
		audience: "consumer",
		title: ["旅行与住宿", "A quiet getaway"],
		description: [
			"选择入住信息、核对价格并完成演示预订。",
			"Choose dates, review the price and finish a demo booking.",
		],
		components: ["Steps", "Form", "Callout"],
		motif: "09",
	},
	{
		id: "showcase-learning",
		audience: "consumer",
		title: ["在线学习", "Learning studio"],
		description: ["浏览课程、阅读内容并记录学习进度。", "Explore lessons, read and record your progress."],
		components: ["Progress", "Button", "Card"],
		motif: "10",
	},
	{
		id: "showcase-music",
		audience: "consumer",
		title: ["音乐播放器", "Music collection"],
		description: ["切换曲目、控制播放状态并收藏音乐。", "Select tracks, control player state and save favorites."],
		components: ["IconButton", "Table", "Badge"],
		motif: "11",
	},
	{
		id: "showcase-wellness",
		audience: "consumer",
		title: ["日常习惯", "Daily rituals"],
		description: ["记录习惯和饮水，观察本周的节奏。", "Log habits and water, and see your weekly rhythm."],
		components: ["Checkbox", "Progress", "BarChart"],
		motif: "12",
	},
] as const;
